name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting (if configured)
      run: npm run lint --if-present

    - name: Run tests
      run: npm test --if-present

    - name: Check addon structure
      run: |
        # Verify essential files exist
        test -f manifest.json || (echo "manifest.json missing" && exit 1)
        test -f addon.js || (echo "addon.js missing" && exit 1)
        test -f server.js || (echo "server.js missing" && exit 1)
        
        # Validate manifest.json
        node -e "JSON.parse(require('fs').readFileSync('manifest.json', 'utf8'))" || (echo "Invalid manifest.json" && exit 1)
        
        echo "✅ Addon structure validation passed"

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified